"""rename address

Revision ID: 277fa5cebe69
Revises: 56c57aeab8ac
Create Date: 2025-11-19 12:25:25.463666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277fa5cebe69'
down_revision = '56c57aeab8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
