"""rename department

Revision ID: 56c57aeab8ac
Revises: 3a9d8a6d4d7d
Create Date: 2025-11-19 12:14:04.206413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c57aeab8ac'
down_revision = '3a9d8a6d4d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
